# Generated by Django 5.1.6 on 2025-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinstance',
            name='year',
            field=models.IntegerField(help_text='Academic year (2018 for 2018-19)'),
        ),
    ]
